title: PeerLLM Blog
email: your-email@example.com
description: >-
  A blog about PeerLLM and related topics in machine learning and AI.
baseurl: ""
url: "https://peerllm.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
